# backend:
#   name: github
#   repo: Hansen-rent/hansen-fe
#   branch: main
#   auth_scope: repo

# backend:
#   name: git-gateway
#   branch: main
backend:
  name: proxy

collections:
  - name: mock
    label: Mock
    extension: json
    format: json
    editor:
      preview: false
    files:
      - label: Asd
        name: qwe
        file: content/global-components/promotions.json
        fields:
          - name: label
            label: Block Label
            widget: string
          - name: items
            label: Cards
            widget: list
            summary: '{{fields.title}}'
            label_singular: card
            fields:
              - name: image
                label: Image
                widget: image
              - name: title
                label: Title
                widget: string
              - name: description
                label: Description
                widget: string
              - name: buttonLabel
                label: Button Label
                widget: string
